### PR TITLE
fix https://github.com/kylemcdonald/ofxCv/issues/163

### PR DESCRIPTION
**Pull request by avilleret**
now we can draw submat silently
but note that `copy(Mat submat, ofImage img)`  may be affected by the same issue.

### CODE REVIEW

**Comment by kylemcdonald** [comment]
thanks! i appreciate this idea but would prefer a different implementation.

ofTexture already has methods for drawing sub-regions, so it would be better to submit a PR that does the following:

1. adds `ofTexture makeTexture(Mat& mat)`
2. uses `makeTexture` inside `drawMat`

then drawing subregions will look like: `makeTexture(mat).draw(x, y, w, h, sx, sy, sw, sh)` and be more flexible with drawing subregions. also, it means you can cache the texture for faster drawing when you need to draw it multiple times.

**Comment by avilleret** [comment]
I agree, and since my method doesn't solve all issues, you're definitively right. 
Unfortunately I don't know OF enough now to be the man to write such a PR.

**Comment by kylemcdonald** [comment]
actually, thinking about this some more, i think the right way to do it is:

```
Mat mat;
ofTexture tex;
ofxCv::copy(mat, tex);
tex.draw(x, y, w, h, sx, sy, sw, sh);
```

in my opinion, this is the right balance of expressivity and simplicity already. if you want to cache the texture it's possible, and you have all the subregion-drawing ability you want. so maybe use that approach, and there's no need for a PR :) thanks!

**Comment by avilleret** [comment]
@kylemcdonald with your code and latest ofxCv I got : 

~~~~
 error: no matching function for call to ‘toCv(ofTexture&)’
~~~~

moreover, the right ofTexture member function seems to be `ofTexture::drawSubsection(float x, float y, float w, float h, float sx, float sy)`

For now, I'm using a function that convert a cv::subMat into ofImage with taking care of ROI :

~~~~
  static void subMat2ofImg(Mat subMat, ofImage& img){
    imitate(img,subMat);
    Mat tmp = toCv(img);
    subMat.copyTo(tmp);
    img.update();
  }
~~~~

Then the image is cached and can be reused.

**Comment by kylemcdonald** [comment]
ok, going reopen this as a reminder to fix the toCv(ofTexture&) thing (really, need to implement the copy() properly).

**Pull request closed without merging**
