### PR TITLE
Useful project and properties file for easy inclusion of addon in VS 2012.

### PR DESCRIPTION
**Pull request by prisonerjohn**

### CODE REVIEW

**Comment by kylemcdonald** [comment]
how does this compare to the branch @elliotwoods made https://github.com/kylemcdonald/ofxCv/tree/VS2012-static ?

this direction seems interesting, but because it's so different to the way libraries are handled on other platforms i probably won't merge it to master.

**Comment by elliotwoods** [comment]
i think it's the same. kyle won't add it which is a bit of a pain.

@prisonerjohn - recommend looking into ofxCvMin if you just want opencv (and don't need kyle's extra classes). That's what i've been using under windows (it has static project file and props. i'm using it with vs2013/x64 right now, but i think it's also good for vs2012/x86).

**Comment by prisonerjohn** [comment]
Oh, hadn't seen @elliotwoods' branch, although I had a feeling someone else had previously done this :)

@kylemcdonald I understand your point. It's unfortunate because adding libs like this one with a bunch of files in a complex folder structure is a total pain in Visual Studio.

And thanks for the recommendation @elliotwoods, I'll take a look.

**Comment by kylemcdonald** [comment]
going to close this as the new project generator is making these kind of tricks unnecessary, if i understand correctly.

**Pull request closed without merging**
