### PR TITLE
Update to glm vectors for 0.10.0+ (aka oF master branch), Add more const utility functions for flexibility.

### PR DESCRIPTION
**Pull request by bakercp**
Updates for 0.10.0+ / aka openFrameworks master branch.
- Updates vectors to glm. 
- Adds more const utility functions.

### CODE REVIEW

**Comment by kylemcdonald** [comment]
it looks like 0.9.4 is about to drop -- should i merge this now (is it 0.9.3 compatible), or wait for the release?

**Comment by bakercp** [comment]
Actually this included glm updates, and it appears that glm is not part of the 0.9.4 updates, so I think it has to wait for 0.10.0.

**Comment by kylemcdonald** [comment]
Going to try bringing an old app up to date. I tried building with the current openframeworks/master and got lots of glm conversion errors, presumably they're exactly what this PR is trying to fix.

Do you recommend I bring my app up to 0.9.4, or should I bring it up to master and use this branch? Are there any advantages to what's currently in master vs 0.9.4?

Also, hey, it's been a while ;) Hope you're well @bakercp

**Comment by kylemcdonald** [comment]
I ended up using 0.9.4 for now. Once that's released then I'll start using openframeworks/master and this branch for my own apps, whatever that may entail... :)

**Comment by bakercp** [comment]
Good choice.  The latest master is pretty great -- the biggest difference is that it's using GLM and there are some breaking changes.  Hope you're well @kylemcdonald as well!

**Comment by armadillu** [comment]
hey guys, do you know if this will this compile against with current master? I'm a bit confused by what 0.10.0+ means

**Comment by bakercp** [comment]
By 0.10.0+ I mean master (as stable is 0.9.*).

**Comment by kylemcdonald** [comment]
i'm trying to use this with 0.9.8 right now, and i think this chunk should be removed completely:

```c++
    // this version copies size and image type
    template <class M, class O> void imitate(M& mirror, O& original) {
        imitate(mirror, original);
    }
```

as it will always cause an infinite recursion. the version above it, which extracts the image type from the original, that's the one that should exist.

**Comment by armadillu** [comment]
yep I had to remove it too

**Comment by bakercp** [comment]
Done.

**Comment by kylemcdonald** [comment]
thanks @bakercp! and for the confirmation @armadillu. this is pulled into develop. i will merge to master in a minute.

**Comment by bakercp** [comment]
Just a note -- as far as I tested, this won't be compatible with the oF stable branch (0.9.*) because of `glm` which isn't included until 0.10.* (thus the PR to develop).

For my addons, I'm now using the `master` branch match the `master` branch of openFrameworks and making my `stable` branch match the oF `stable` branch.  Perhaps to eliminate any confusion with this addon, we should keep the updates in the master branch (which is now incompatible with oF stable) and make a stable tag / branch like the openFrameworks version does?

@batchku https://github.com/kylemcdonald/ofxCv/issues/208

**Comment by bakercp** [comment]
Here's what I mean w/ my addon branching structure:

https://github.com/bakercp/ofxIO#compatibility

**Comment by kylemcdonald** [comment]
@bakercp thanks. i made a stable branch for 0.9.8, and added a note near the top of the readme. i didn't really understand what was going on with glm until you explained it just now. being outside regular OF discussion makes me wish there was a short note at the top of the OF readme (or somewhere else accessible) about very short-term plans for OF, for people who are trying to maintain addons and projects but can't keep up with all the development.

**Pull request merged**
